name: briefing
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^1.1.6+3
#  moor_flutter: ^1.6.0
  url_launcher: ^5.1.2
  share: ^0.6.2+1
  intl: ^0.15.8
  http: ^0.12.0+2
  rxdart: ^0.22.1
  cached_network_image: ^1.1.1
  flutter_custom_tabs: ^0.6.0
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/no_internet.png

  fonts:
    - family: Libre_Franklin
      fonts:
        - asset: assets/fonts/Libre_Franklin/LibreFranklin-Regular.ttf
        - asset: assets/fonts/Libre_Franklin/LibreFranklin-Bold.ttf
          weight: 700
    - family: Crimson_Text
      fonts:
        - asset: assets/fonts/Crimson_Text/CrimsonText-Regular.ttf
        - asset: assets/fonts/Crimson_Text/CrimsonText-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Crimson_Text/CrimsonText-Bold.ttf
          weight: 700
